### ISSUE TITLE
Error when attempting to reinstall traefik

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#183]
# Issue Template

## When reinstalling traefik - that is, the app directory already exists from a previous install - jailman will throw an error
This may be related to issue #182 during initial creation, tbd whether that's connected

### Detailed Bug Report
Ports not enabled for blueprint, skipping
Jail creation completed for traefikjail
ERROR, No valid install detected in config directory but files present
ERR - status code 1
Command:  "${SCRIPT_DIR}"/blueprints/"${!blueprint}"/install.sh "${jail}"
Location:  ./jailman.sh, line 171
Status: 0
Stack trace:
    [1] main(): ./jailman.sh, line 171 -> main

Install script did not finish, sysrc missing:

root@traefikjail:~ # sysrc -a
cron_flags:  -J 15
hostname: traefikjail
ipv6_activate_all_interfaces: YES
sendmail_enable: NO
sendmail_msp_queue_enable: NO
sendmail_outbound_enable: NO
sendmail_submit_enable: NO
syslogd_flags: -c -ss

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1. ./jailmain.sh -i traefikjail  
2.  ./jailmain.sh -d traefikjail 
3.  ./jailmain.sh -i traefikjail

**Comment by Ornias1993** [comment]
Thanks for your report, will look into this after 1.2.3 merge! :)

**Comment by Ornias1993** [comment]
Okey, i've looked into this anyhow:
In 1.3.0, reinstall and failure handling has been redesigned, to prevent botched installs botching future reinstalls:
- If an install finishes correctly, it addes an INSTALLED file to the config folder
- Any install checks for said file and flags a reinstall if present
- If the file is not present, but other files are, this means a previous install has failed and the config in that directory might be corrupted.

In you case, if your previous install failed in #182 this is a logical consequence: If #182 already put files in the config folder, it prevents another try to install. You need to manually add the INSTALLED file or remove/wipe the dataset.

This is not automated, because we don't want to screw with the users data ourselves. Only the user can determine if they want to override by adding the file, remove all files from the directory or repair manually.

So, I think it's best closing this, as this issue is an intended consequence from trying to install after an install failure....
If not, please say so and feel free to reopen!
