### ISSUE TITLE
Feature: Safer bash

### ISSUE THREAD

**Issue by disconn3ct** [jailmanager/jailman#48]
As an end-user, I would prefer if the script exited on error instead of continuing to make changes. Additionally, it would be nice to run static analysis (shellcheck)

For example, https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/ documents some settings that can manage errors and even clean up after failures (ERR trap)

**Comment by Ornias1993** [comment]
I totally forgot to add a shellcheck issue, thanks for adding. Yes this is prefered.

If an individual jail throws an error, it should stop creating said jail indeed.
But there are some edge cases to error handling that should also be checked, there are currently some edge cases where a failure during creation requires manual internvention to delete created files (because it would otherwise think it's a reinstall)

**Comment by Ornias1993** [comment]
To give an update:
- Previous version we added shellcheck repo wide
- Currently some code has been refactored to work with stricter bash settings.

To completely finish this would be something for the long(er) term, because it means going over a lot of the code.

**Comment by Ornias1993** [comment]
@asmod3us Could you look at testing some more parts of the code with stricter bash settings?
It's not my specialty honestly...

**Comment by asmod3us** [comment]
Yep, I'll look into this

**Comment by Ornias1993** [comment]
Closed due to being fixed in the dev branch
