### ISSUE TITLE
Create "shareable" datasets with SMB shares in mind

### ISSUE THREAD

**Issue by thorsteneb** [jailmanager/jailman#63]
Improve creation for datasets that are intended to be shared via SMB, such as media. Potentially also downloads?

1) Create case-insensitive, see https://www.ixsystems.com/blog/windows-smb-shares-on-freenas/

To Be Discussed, this could be helpful:

- global yaml contains group name for users, will default to "shared" if not set
- Set owner and group of shareable datasets to "nobody" and [group name]
- Set default FACLs, same that FreeNAS would set when choosing "SMB Share"

**Comment by Ornias1993** [comment]
1. is fine.

The rest i'm not going to mess too much with, considering I even still need to fix permissions in the first place ;)

**Comment by Ornias1993** [comment]
Downloads isn't supposed to be shared though.
It's very tricky at times to get permissions right.

If people want to upload their own content for plex, sonarr, radarr etc, we should rather create a SMB-proof upload dataset.

**Comment by thorsteneb** [comment]
1) is all I'm really concerned with. Doing an SMB share on media can be up to the user, and if downloads isn't meant to be shared and case-sensitivity is desirable (and/or not a performance drag), then leave it as is

My use case may be different from what other people are doing. I am not using the *arr applications, and never will. I use Plex for space-shifted movies, tv shows and music that I own the physical media for. If I don't have physical media, it doesn't go on Plex. That's as far as I am willing to bend the rules of copyright.

And that means that sharing those folders to Windows is very much desired, so I can do that space-shifting from there.

I know that's not everyone's use case. I have no idea how common it is to use Plex and not use any download or torrent sites.

**Comment by Ornias1993** [comment]
Indeed it would be desired to make Media shareable.
Downloads is primarily meant for *arr applications...

But I think we agree on this one in essence.

**Comment by Ornias1993** [comment]
@thorsteneb I read into the guide by IX, but I cant find good definitive examples of CLI implementations.

If you find how to setup media to be more SMB friendly using the CLI, i'm open for input on that one.

**Comment by thorsteneb** [comment]
Here's how you can create a dataset from CLI that is "share-friendly" and will show up as type ACL in FreeNAS 11.3.
Note: TrueNAS 12 Core, look into acltype and xattr attributes and see how TrueNAS handles those.

aclmode                 restricted              local
casesensitivity         insensitive

```
zfs create -o aclmode=restricted -o casesensitivity=insensitive tank/test-dataset
setfacl -m owner@:rwxpDdaARWcCos:fd-----:allow,group@:rwxpDdaARWcCos:fd-----:allow,everyone@:r-x---a-R-c---:fd-----:allow,user:972:rwxpDdaARWcCos:fd-----:allow /mnt/tank/test-dataset
chown nobody:wheel /mnt/tank/test-dataset
```

That chown should ideally be for nobody:CUSTOMUSERGROUP to allow easy access from Windows / SMB. CUSTOMUSERGROUP is whatever the FreeNAS admin has set for their users that log in from Windows.
Could be handled with a note to please change that; or with a variable; or with a note if no variable is supplied

**Comment by Ornias1993** [comment]
I'm okey with setting -o casesensitivity=insensitive on media...

But for the whole sharing thing:
I need a whole permissions design, including the *arr systems, because i'm not that well versed into the whole ACL thing.

**Comment by thorsteneb** [comment]
ACLs are fairly simple in this example. Assume nobody:shared as owner:group for the dataset, with "shared" being the group that all manually created local users that should have access belong to. Those local users are what you'd authenticate to via SMB share.

So in this setup:
Owner has full control, sure.
Group has full control, that's really what gives all users the ability to do stuff
Everyone has read access, that's more for stuff like "LMS needs to be able to read the music" and such
972 (Plex) has full control

If you have specific users in *arr that need full control, you'd simply add them to the setfacl.

Related note: Whether having a dataset with three child datasets, instead of a dataset with three folders, is desirable, is very debatable.
Pro: Ability to set ACLs granularly, ditto for snapshots
Con: See Pro. Users already struggle with ACLs, now you're asking them to manage this in four places instead of one.

On my system, I have one media dataset with the ACL you see above, and then three folders for movies, tv shows and music. That way, I do not need to set / manage individual ACLs for individual media types.
I also have only one snapshot set for all media types, but that's fine for my use case.

**Comment by Ornias1993** [comment]
Hmm..
The thing is, I don't want it to become "share manager"...

It puts the burden for working shares on me/us and considering the amount of support requests IX is recieving for it, I want to stay as FAR as possible from shares.

Currently we can say:
"the moment you started messing with ACL's, you knew we did not actively support it"
The moment we start adding ACL ourselves we are the focus point if ACL's don't work out well.

When I add to this the expected OpenZFS migration I expect quite some ACL issues in the comming 2 year and I'm not ready for them.

That being said: I'm all for making media case insensitive. 
But that being said, where will it stop... Now we do media, next people want jailx data to be case insensitive too...

It also increases the burden for blueprint maintainers when they even need to think about ACL's.

So maybe we should just expect people that want a custom dataset to... create a custom dataset?
Like we do already, because our datasets for media aren't optimal anyway.

Conclusion:
I've decided to close this issue. While I will not deny a PR for it if it comes in, chances are it is not going to get merged because of above issues.

So it isn't a "won't fix", it's a "free to fix, but not actively worked towards".

It's like a very obscure, hard to maintain blueprint: you are free to add it, but it has not place in the issue list...
